name: pr

on:
  push:
  pull_request:

# Common Go workflows from go faster
# See https://github.com/go-faster/x
jobs:
  test:
    uses: go-faster/x/.github/workflows/main.yml@main
  lint:
    uses: go-faster/x/.github/workflows/lint.yml@main
  commit:
    uses: go-faster/x/.github/workflows/commit.yml@main
